#!/bin/sh
GIT_ANNEX_PROGRAMPATH="$0"
export GIT_ANNEX_PROGRAMPATH
exec "$GIT_ANNEX_DIR/exe/git-hash-object" --library-path "$GIT_ANNEX_LD_LIBRARY_PATH" "$GIT_ANNEX_DIR/shimmed/git-hash-object/git-hash-object" "$@"
