#!/bin/sh
GIT_ANNEX_PROGRAMPATH="$0"
export GIT_ANNEX_PROGRAMPATH
exec "$GIT_ANNEX_DIR/exe/git-for-each-ref" --library-path "$GIT_ANNEX_LD_LIBRARY_PATH" "$GIT_ANNEX_DIR/shimmed/git-for-each-ref/git-for-each-ref" "$@"
