#!/bin/sh
# Change registration email address.
set -e

./prompt-email
registrationemail="$(cat .registrationemail)"

for shard in $(echo shard* 2>/dev/null); do
	echo "Updating $shard"
	if [ -d "$shard" ]; then
		SHARD="$(echo "$shard" | tr a-z A-Z)"
		uuid="$(cd $shard && git config annex.uuid)"
		wget -O- "$(./register-helper.pl "$SHARD" "$uuid" "$registrationemail" "$(cat id_rsa.pub)")"
	fi
done

echo ""
echo "Your email address should be updated now."
