#!/bin/sh
set -e

shard="$1"
if [ -z "$shard" ]; then
	echo "Usage: checkoutshard shardN" >&2
	exit 1
fi
SHARD="$(echo "$shard" | tr a-z A-Z)"

if [ -d "$shard" ]; then
	echo "$shard already checked out"
	exit 0
fi

case "$(uname)" in
	Darwin)
		PATH=$(pwd)/git-annex.osx:$PATH
		;;
	*)
		PATH=$(pwd)/git-annex.linux:$PATH
		;;
esac
export PATH

top="$(pwd)"
prevshard="$(echo shard* 2>/dev/null | cut -d ' ' -f 1)"

if [ ! -e .registrationemail ]; then
	./prompt-email
fi
registrationemail="$(cat .registrationemail)"

checkssh () {
	repourl="$1"
	
	if [ ! -e id_rsa ]; then
		ssh-keygen -q  -P "" -t rsa -f ./id_rsa
	fi
	
	user="$(echo "$repourl" | cut -d : -f 1)"
	dir="$(echo "$repourl" | cut -d : -f 2)"

	echo "Checking ssh to server at $repourl..."
	if ! ssh -i id_rsa -o BatchMode=yes -o StrictHostKeyChecking=no "$user" git-annex-shell -c configlist "$dir"; then
		echo "Seem you're not set up yet for access to $repourl yet. Let's fix that.."
		wget -O- "http://iabak.archiveteam.org/cgi-bin/register.cgi?shard=$SHARD&email=$registrationemail&pubkey=$(tr '+' '_' < id_rsa.pub)"
		sleep 1
		wget -q -O- http://iabak.archiveteam.org/cgi-bin/pushme.cgi >/dev/null 2>&1 || true
		checkssh "$repourl"
	fi
}

l=$(grep -i "^$shard " repolist)
if [ -z "$l" ]; then
	echo "Shard not found in repolist" >&2
	exit 1
fi
set -- $l
localdir="$1"
repourl="$2"
status="$3"

checkssh "$repourl"

# This is slightly weird way to clone, but it allows using our
# dedicated ssh key without installing it in ~/.ssh/
git init "$localdir"
cd "$localdir"
git config user.name "$(whoami)"
git config user.email "$(whoami)@iabak"
git config gc.auto 0
git annex init
cp -a ../id_rsa .git/annex/id_rsa
cp -a ../id_rsa.pub .git/annex/id_rsa.pub
git remote add origin "$repourl"
git config remote.origin.annex-ssh-options "-i .git/annex/id_rsa"
git annex sync

# Copy over any user configuration from a previous shard.
cd "$top"
if [ -n "$prevshard" ]; then
	for c in annex.diskreserve annex.web-options; do
		val="$(cd "$prevshard" && git config "$c" || true)"
		if [ -n "$val" ]; then
			(cd "$localdir" && git config "$c" "$val")
		fi
	done
fi

echo "Checked out $localdir for $shard (from $repourl). Current status: $status"
