#!/bin/sh
set -e

NUMCOPIES=4

LANG=C
export LANG

echo "Welcome to iabak version 0.1"
echo "ALPHA TEST, use with caution"
echo

case "$(uname)" in
	Darwin)
		PATH=$(pwd)/git-annex.osx:$PATH
		;;
	*)
		PATH=$(pwd)/git-annex.linux:$PATH
		;;
esac
export PATH

if FLOCK=$(which flock); then
	FLOCK="${FLOCK} -x -n"
else
	FLOCK="$(pwd)/flock.pl"
fi

pow () {
	local x=${1:-1} y=${2:-0} result=${3:-1}
	if [ ${y} -gt 0 ]; then
		echo "$(pow "${x}" "$((y-1))" "$((result*x))")"
	else
		echo "${result}"
	fi
}

# I can wikipedia
# sh is annoying, so you must call rand_update (and not from a
# subshell) to update the state variable, then you can call rand to
# read it
RANDOM_SEED=$$
rand_update () {
	RANDOM_SEED="$((1664525 * RANDOM_SEED + 1013904223))"
}
rand () {
	local max=${1}
	if [ -z "${max}" ]; then
		echo "${RANDOM_SEED}"
	else
		local r="$((RANDOM_SEED % max))"
		if [ ${r} -lt 0 ]; then
			echo "$((r * -1))"
		else
			echo "${r}"
		fi
	fi
}

# syncs a shard with random exponential backoff in case of failure, and a maximum of 4 retries.
syncshard () {
	# assumes that pwd is a shard
	local retries=0
	while [ ${retries} -lt 5 ]; do
		if git annex sync; then
			return 0
		fi
		retries=$((retries+1))
		rand_update
		sleep "$(rand "$(pow "2" "${retries}")")"
	done
	return 1
}

download () {
	syncshard || echo "Warning: Failed to sync this shard; working off of data which is potentially out of date."
	periodicsync &

	echo "Here goes! Downloading from Internet Archive."
	echo "(This can be safely interrupted at any time with ctrl-C)"
	echo "(Also, you can safely run more than one of these at a time, to use more bandwidth!)"
	echo ""
	if rundownloaddirs; then
		echo
		echo "Wow! I'm done downloading this shard of the IA!"
	else
		echo 
		echo "Download finished, but the backup of this shard is not fully complete."
		echo "Some files may have failed to download, or all allocated disk space is in use."
	fi
}

rundownloaddirs () {
	if [ ! -e ../NOSHUF ] && [ -x /usr/bin/shuf ] && dirname -z foo >/dev/null 2>&1 ; then
		echo "(Oh good, you have shuf(1)! Randomizing order.. Will take a couple minutes..)"
		git annex find --print0 --not --copies "$NUMCOPIES" | xargs --no-run-if-empty -0 dirname -z -- | uniq -z | shuf -z | xargs --no-run-if-empty -n 100 -0 git -c annex.alwayscommit=false annex get --
	else
		git annex get --not --copies "$NUMCOPIES"
	fi
}

rundownloadfiles () {
	echo "Checking for any files that still need to be downloaded..."
	if [ ! -e ../NOSHUF ] && [ -x /usr/bin/shuf ]; then
		# don't use dirname here, because in maint mode,
		# only 1 file from a dir might go missing and we 
		# don't want to download the whole dir then
		git annex find --print0 --not --copies "$NUMCOPIES" | shuf -z | xargs --no-run-if-empty -n 100 -0 git -c annex.alwayscommit=false annex get --
	else
		git annex get --not --copies "$NUMCOPIES"
	fi
}

fsckme () {
	set +e
	if [ -e ../FSCKTIMELIMIT ]; then
		FSCKTIMELIMIT="$(cat ../FSCKTIMELIMIT)"
	fi
	if [ -z "$FSCKTIMELIMIT" ]; then
		FSCKTIMELIMIT=5h
	fi
	${FLOCK} .git/annex/fullfsck.lock git annex fsck --incremental-schedule 30d --time-limit "$FSCKTIMELIMIT"
	fsckresult=$?
	set -e
	if [ "$fsckresult" -eq 101 ]; then
		echo "Incremental full fsck ran out of time, will continue it next run."
	fi
}

fastfsck () {
	# The point of this is just to report that the repository still
	# exists, to prevent it from expiring.
	# Even a fsck --fast --in here is a litte too slow to run
	# frequently.
	if [ ! -d .empty ]; then
		mkdir .empty
	fi
	git annex fsck --fast .empty --quiet >/dev/null 2>/dev/null || true
	syncshard || echo "Warning: failed to sync this shard; fsck results not recorded on server"
}

maint () {
	echo "This shard is in maintenance mode; checking it."
	fsckme

	if [ ! "$CRONJOB" ]; then
		syncshard || (echo "Error: failed to sync shard in maintenance mode"; exit 1)
		periodicsync &
		if rundownloadfiles; then
			echo ""
			echo "This shard remains in good shape!"
		else
			echo 
			echo "Could not fully maintain this shard."
			echo "Some files may have failed to download, or all allocated disk space is in use."
		fi
	fi
}

periodicsync () {
	${FLOCK} .git/annex/iasyncer.lock ../iabak-hourlysync || true
}

outofspace () {
	reserve="$1"
	which numfmt >/dev/null 2>&1 && [ $(df -Ph . | tail -1 | awk '{print $4}' | numfmt --from=si) -lt $(echo $reserve | numfmt --from=si) ]
}

stillhavespace () {
	prevshard="$(echo shard* 2>/dev/null | cut -d ' ' -f 1)"

	if [ -n "$prevshard" ]; then
		reserve="$(cd "$prevshard" && git config annex.diskreserve || true)"
		if [ -n "$reserve" ] && outofspace "$reserve"; then
			false
		else
			true
		fi
	else
		true
	fi
}

setup () {
	echo ""
	df -h .
	echo "How much of this disk space do you want to keep free, and not use for IA backup?"
	echo "(You can free up space at any time.)"
	echo "To use entire disk, just hit Enter, or type in something like"
	echo "200G or 1T"
	printf "keep free> "
	read reserve
	if [ -n "$reserve" ]; then
		if outofspace "$reserve"; then
			echo "not enough diskspace to reserve"
			setup
		else
			git config annex.diskreserve "$reserve"
		fi
	fi
	echo "Now we need to set up a service to regularly double-check the content of"
	echo "your backup. This protects the backup against bit-rot."
	./install-fsck-service
}

installgitannex () {
	${FLOCK} .iabak-install-git-annex ./install-git-annex || true
}

installfsckservice () {
  ${FLOCK} ./iabak-install-fsck-service ./install-fsck-service || true
}

handleshard () {
	shard="$1"

	echo
	echo "========= $shard ========="
	echo
	
	l="$(grep "^$shard " repolist | head -n 1)"
	set -- $l
	state="$3"

	cd "$shard"
	case "$state" in
		active)
			if [ ! "$CRONJOB" ]; then
				download
			fi
		;;
		reserve)
			if [ ! "$CRONJOB" ]; then
				download
			fi
		;;
		maint)
			maint
		;;
		restore)
			echo "TODO: upload" >&2
		;;
		*)
			echo "unknown state $state for shard $shard" >&2
		;;
	esac

	syncshard || echo "Warning: failed to sync shard; results of download not known to be recoded on the server."
}

# Order with newest checked out shards first.
sharddirs () {
	perl -le 'foreach (@ARGV) { $ctime=((stat($_))[10]); print "$ctime $_" if -d $_ }' shard* | sort -rn | cut -d ' ' -f 2
}

randomshard () {
	wantstate="$1"
	grep " $wantstate$" repolist | cut -d ' ' -f 1 | perl -e 'while (<>) { chomp; if (! -d $_) { push @l, $_ } };  print $l[rand @l]'
}

randomnew () {
	active="$(randomshard active)"
	if [ -z "$active" ]; then
		randomshard reserve
	else
		echo "$active"
	fi
}

if [ -n "$(sharddirs)" ]; then
	./install-fsck-service
	installgitannex

	# First do a fast fsck of all shards, in order to detect
	# obvious problems, and report in that we still have the data
	# we said we have.
	for d in $(sharddirs); do
		(cd "$d" && fastfsck)
	done

	# Now the expensive processing of each shard.
	for d in $(sharddirs); do
		( handleshard "$d" )
	done
	
	# Move clients on to next shards.
	if ! [ -e NOMORE ] && [ ! "$CRONJOB" ]; then
		while stillhavespace; do
			new="$(randomnew)"
			if ! [ -z "$new" ]; then
				echo ""
				echo "Looks like you still have free disk space, so I will continue to fill it up!"
				echo "(ctrl-c and touch NOMORE to prevent this behavior..)"
				echo ""
				./checkoutshard "$new"
				( handleshard "$new" )
			else
				echo ""
				echo "Looks like we ran out of shards for you to download before you ran out of disk space. Please try again later!" >&2
				exit 0
			fi
		done
		echo ""
		echo "Filled up available disk space, so stopping here!"
	fi
else
	if [ "$CRONJOB" ]; then
		echo "running as cron job, but have no shards, so doing nothing" >&2
		exit 1
	fi

	localdir="$(randomnew)"
	if [ -z "$localdir" ]; then
		echo "No new shards are currently available. Please try again later!" >&2
		exit 1
	fi

	echo "Looks like this is a new IA backup. I'm going to put it in"
	echo "$(pwd)/$localdir"
	echo "This will use some disk space. :)"
	printf "Press Enter to confirm, or ctrl-C to cancel."
	read confirm

	installgitannex
	./checkoutshard "$localdir"
	(
		cd "$localdir"
		setup
		periodicsync &
		download
	)
fi
