#!/bin/sh
list=$1
wc -l "$list"
perl -lne 'my ($md5, $size, $coll, $url)=split("\t", $_,4); $file=$url; $file=~s/https:\/\/archive.org\/download\///; $file="$coll/$file"; if ($file=~/_files.xml$/) { $url=~s/:/&c/g; $url=~s/\//%/g; print ("URL--".$url." ".$file) } else { print ("MD5-s".$size."--".$md5." ".$file) }' < "$list" | git -c annex.alwayscommit=false annex fromkey --force
perl -lne 'my ($md5, $size, $coll, $url)=split("\t", $_,4); if ($url=~/_files.xml$/) { $kurl=$url; $kurl=~s/:/&c/g; $kurl=~s/\//%/g; print ("URL--".$kurl." ".$url) } else { print ("MD5-s".$size."--".$md5." ".$url) }' < "$list" | git -c annex.alwayscommit=false annex registerurl
git annex merge
