#!/bin/sh
set -e

if [ -d git-annex.linux ]; then
	# if an installed version exists, check the version-number
	installedVersion=$(./git-annex.linux/git-annex version | grep "version" -m 1 | sed 's/^.*\([0-9]\+\)\.\([0-9]\{8\}\).*$/\2/' | tr '\n' ' ')
	newVersion=$(wget https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-i386.tar.gz.info -o /dev/null -O - | sed 's/.*distributionReleasedate = \([0-9]\{4\}\)-\([0-9]\{2\}\)-\([0-9]\{2\}\).*UTC,.*/\1\2\3/' | tr '\n' ' ')
	if [ "$installedVersion" -lt "$newVersion" ]; then
		rm -rf git-annex.linux
	fi
fi

if [ ! -d git-annex.linux ]; then
	echo "Installing a recent version of git-annex ..."
	rm -f git-annex-standalone-i386.tar.gz
	wget https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-i386.tar.gz
	tar xf git-annex-standalone-i386.tar.gz
	rm -f git-annex-standalone-i386.tar.gz
	echo "Installed in $(pwd)/git-annex.linux"
	echo
fi
