#!/bin/sh
set -e

# should normally be 0
NEED_PRERELEASE=1

linux_install () {
    ARCH=""
    UNAME_M="$(uname -m)"
    case $UNAME_M in
        'x86_64') ARCH="amd64";;
        arm*l) ARCH="armel";;
        i*86) ARCH="i386";;
        *) echo "ERROR: Unhandled architecture: $UNAME_M"; exit 1;;
    esac
	if [ -d git-annex.linux ]; then
		if upgrade_avail ./git-annex.linux/git-annex https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-"$ARCH".tar.gz.info; then
			rm -rf git-annex.linux
		fi
		if [ "$NEED_PRERELEASE" = 1 ] && ! [ -e git-annex.linux/.prerelease ]; then
			rm -rf git-annex.linux
		fi
	fi

	if [ ! -d git-annex.linux ]; then
		echo "Installing a recent version of git-annex ..."
		rm -f git-annex-standalone-"$ARCH".tar.gz
		if [ "$NEED_PRERELEASE" = 1 ]; then
			wget https://downloads.kitenet.net/git-annex/autobuild/"$ARCH"/git-annex-standalone-"$ARCH".tar.gz
		else 
			# released version
			wget https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-"$ARCH".tar.gz
		fi
		tar xf git-annex-standalone-"$ARCH".tar.gz
		if [ "$NEED_PRERELEASE" = 1 ]; then
			touch git-annex.linux/.prerelease
		fi
		rm -f git-annex-standalone-"$ARCH".tar.gz
		echo "Installed in $(pwd)/git-annex.linux"
		echo
	fi
}

osx_install () {
	if [ -d git-annex.osx ]; then
		if upgrade_avail ./git-annex.osx/git-annex https://downloads.kitenet.net/git-annex/OSX/current/10.10_Yosemite/git-annex.dmg.info; then
			rm -rf git-annex.osx
		fi
		if [ "$NEED_PRERELEASE" = 1 ] && ! [ -e git-annex.osx/.prerelease ]; then
			rm -rf git-annex.osx
		fi
	fi

	if [ ! -d git-annex.osx ]; then
		echo "Installing a recent version of git-annex ..."
		rm -f git-annex.dmg
		if [ "$NEED_PRERELEASE" = 1 ]; then
			wget https://downloads.kitenet.net/git-annex/autobuild/x86_64-apple-yosemite/git-annex.dmg
		else 
			# released version
			wget https://downloads.kitenet.net/git-annex/OSX/current/10.10_Yosemite/git-annex.dmg
		fi
		mkdir git-annex.osx.mnt
		hdiutil attach git-annex.dmg -mountpoint git-annex.osx.mnt
		cp -r git-annex.osx.mnt/git-annex.app/Contents/MacOS/ git-annex.osx
		hdiutil eject git-annex.osx.mnt
		if [ "$NEED_PRERELEASE" = 1 ]; then
			touch git-annex.osx/.prerelease
		fi
		rm -f git-annex.dmg
		rm -rf git-annex.osx.mnt
		echo "Installed in $(pwd)/git-annex.osx"
		echo
	fi
}

upgrade_avail () {
	cmd="$1"
	infourl="$2"

	installedVersion="$($cmd version --raw 2>/dev/null | cut -d '-' -f 1 | cut -d . -f 2)"
	if [ -z "$installedVersion" ]; then
		installedVersion=0
	fi
	newVersion=$(wget $infourl -o /dev/null -O - | sed 's/.*distributionVersion = "[0-9].\([0-9]*\)".*/\1/')
	test -n "$newVersion" && test "$installedVersion" -lt "$newVersion"
}

case "$(uname)" in
	Darwin)
		osx_install
		;;
	*)
		linux_install
		;;
esac
