#!/bin/sh
set -e
set -x

list=$1
num=$2
if [ -z "$list" ] || [ -z "$num" ]; then
	echo "usage: mkSHARD collection-list N" >&2
	exit 1
fi

IFS="
"

cp "$1" "SHARD$num.list"
wc -l "SHARD$num.list"
git init "SHARD$num"
cd "SHARD$num"
git annex init
../importlist ../"SHARD$num.list"
git commit --quiet -a -m "creating SHARD$num"
git annex dead .
git gc --aggressive
git annex info .
cd ..
git clone "SHARD$num" "SHARD$num".git --bare
rm -rf "SHARD$num"
