#!/bin/sh
set -e

list=$1
num=$2
if [ -z "$list" ] || [ -z "$num" ]; then
	echo "usage: mkSHARD collection-list N" >&2
	exit 1
fi

if [ -f "$list" ]; then
	listfile="$list"
	list=""
	for l in $(cat listfile); do
		list="$list $l"
	done
fi

for w in $list; do
	if grep -Fx "$w" /var/www/html/stats/ALL.collections; then
		echo "$w is already in a shard" >&2
		exit 1
	fi
done

rm -f 
IFS="
"
./extract_collection "$1" > "SHARD$num.list"
wc -l "SHARD$num.list"
git init "SHARD$num"
cd "SHARD$num"
git annex init
../importlist ../"SHARD$num.list"
git commit --quiet -a -m "creating SHARD$num"
git annex dead .
git gc --aggressive
git annex info .
cd ..
git clone "SHARD$num" "SHARD$num".git --bare
rm -rf "SHARD$num"
