#!/bin/sh
set -e

getemail () {
	printf "email address> "
	read e1
	if ! echo "$e1" | grep -q '@'; then
		echo "That does not look like an email address. Try again.." >&2
		getemail
	fi
	if ! echo "$e1" | grep -q '\.'; then
		echo "That does not look like an fully qualified domain. Try again.." >&2
		getemail
	fi
	if echo "$e1" | grep -q ' '; then
		echo "Please enter a bare email@example.com address. It cannot contain any spaces." >&2
		getemail
	fi
	printf "re-enter email address to verify> "
	read e2
	if [ "$e1" = "$e2" ] && [ ! -z "$e1" ]; then
		echo "Thanks!"
	else
		echo "Emails don't match! Try again.." >&2
		getemail
	fi
	echo "$e1" > .registrationemail
}
echo ""
echo "To register to participate in the IA.BAK project, please"
echo "enter a contact email address."
echo ""
echo "We will keep this email private, and only use it to contact"
echo "you if there is a problem with your portion of the Internet"
echo "Archive backup."
echo ""
echo "It's important we have a way to get in touch with you,"
echo "so that this backup can be as reliable as possible!"
echo ""
getemail
