#!/bin/sh
# Sets up git repo for a specified SHARD
set -e

SHARD="$1"
TAR="$2"
if [ -z "$SHARD" ] || [ -z "$TAR" ]; then
	echo "Usage: setupshardrepo SHARDn repo.tar.gz" >&2
	exit 1
fi
shard="$(echo "$SHARD" | tr A-Z a-z)"

useradd "$SHARD"
mkdir /home/"$SHARD"
cd /home/"$SHARD"
tar xf "$TAR"
cat > /home/"$SHARD"/.gitconfig <<EOF
[user]
	email = $SHARD@ia-bak
	name = $SHARD
EOF
mkdir /home/"$SHARD"/.ssh
chown -R "$SHARD:$SHARD" /home/"$SHARD"

GITDIR="/home/$SHARD/$shard.git"
ln -sf /usr/local/IA.BAK/hooks/update "$GITDIR/hooks/update"
ln -sf /usr/local/IA.BAK/hooks/post-receive "$GITDIR/hooks/post-receive"

/usr/local/IA.BAK/update-authorized_keys "$SHARD"
