#!/bin/sh
set -e
set -x

collection=${1}
itemfile=${collection}-ids.txt
ia-mine --secure -c -s "collection:${collection}" --itemlist >"${itemfile}"
lines=$(wc -l "${itemfile}" | cut -d ' ' -f 1)
chunks=$((lines/100000))
split -nl/${chunks} -d --additional-suffix=.txt "${itemfile}" "${collection}-meta-"
for f in ${collection}-meta-*.json; do
    ia-mine --secure -c "${f}" > "$(basename "${f/meta/files/}" .json).txt"
done
