.TH git-annex-vcycle 1
.SH NAME
git\-annex vcycle \- switch view to next layout
.PP
.SH SYNOPSIS
git annex vcycle
.PP
.SH DESCRIPTION
When a view involves nested subdirectories, this cycles the order.
.PP
For example, when the view is by year/author/tag, \fBvcycle\fP will switch
it to author/tag/year.
.PP
.SH SEE ALSO
git\-annex(1)
.PP
git\-annex\-view(1)
.PP
git\-annex\-vpop(1)
.PP
git\-annex\-vadd(1)
.PP
git\-annex\-vfilter(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

