.TH git-annex-vicfg 1
.SH NAME
git\-annex vicfg \- edit git\-annex's configuration
.PP
.SH SYNOPSIS
git annex vicfg
.PP
.SH DESCRIPTION
Opens EDITOR on a temp file containing all of git\-annex's global 
configuration settings, and when it exits, stores any
changes made back to the git\-annex branch.
.PP
.SH SEE ALSO
git\-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

