.TH git-annex-vfilter 1
.SH NAME
git\-annex vfilter \- filter current view
.PP
.SH SYNOPSIS
git annex vfilter \fB[tag ...] [field=value ...] [!tag ...] [field!=value ...]\fP
.PP
.SH DESCRIPTION
Filters the current view to only the files that have the
specified field values and tags.
.PP
.SH SEE ALSO
git\-annex(1)
.PP
git\-annex\-view(1)
.PP
git\-annex\-vpop(1)
.PP
git\-annex\-vadd(1)
.PP
git\-annex\-vcycle(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

