.TH git-annex-readpresentkey 1
.SH NAME
git\-annex readpresentkey \- read records of where key is present
.PP
.SH SYNOPSIS
git annex readpresentkey \fBkey uuid\fP
.PP
.SH DESCRIPTION
This plumbing\-level command reads git\-annex's records about whether
the specified key's content is present in the remote with the speficied
uuid.
.PP
It exits 0 if the key is recorded to be present and 1 if not.
.PP
Note that this does not do an active check to verify if the key
is present. To do such a check, use checkpresentkey(1)
.PP
.SH SEE ALSO
git\-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

