.TH git-annex-dead 1
.SH NAME
git\-annex trust \- hide a lost repository
.PP
.SH SYNOPSIS
git annex dead \fB[repository ...]\fP
.PP
.SH DESCRIPTION
Indicates that the repository has been irretrievably lost.
(To undo, use semitrust.)
.PP
Repositories can be specified using their remote name, their
description, or their UUID.
.PP
.SH SEE ALSO
git\-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

