.TH git-annex-undo 1
.SH NAME
git\-annex undo \- undo last change to a file or directory
.PP
.SH SYNOPSIS
git annex  \fB[filename|directory] ...\fP
.PP
.SH DESCRIPTION
When passed a filename, undoes the last change that was made to that
file.
.PP
When passed a directory, undoes the last change that was made to the
contents of that directory.
.PP
Running undo a second time will undo the undo, returning the working
tree to the same state it had before. In order for undoing an undo of
staged changes, any staged changes are first committed by the
undo command.
.PP
Note that this does not undo get/drop of a file's content; it only
operates on the file tree committed to git.
.PP
.SH SEE ALSO
git\-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

