.TH git-annex-semitrust 1
.SH NAME
git\-annex semitrust \- return repository to default trust level
.PP
.SH SYNOPSIS
git annex semitrust \fB[repository ...]\fP
.PP
.SH DESCRIPTION
Returns a repository to the default semi trusted state.
.PP
Repositories can be specified using their remote name, their
description, or their UUID. For the current repository, use "here".
.PP
.SH SEE ALSO
git\-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

