.TH git-annex-xmppgit 1
.SH NAME
git\-annex xmppgit \- git to XMPP relay
.PP
.SH SYNOPSIS
git annex xmppgit
.PP
.SH DESCRIPTION
This command is used internally by the assistant to perform git pulls over XMPP.
.PP
.SH SEE ALSO
git\-annex(1)
.PP
git\-annex\-assistant(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

