.TH git-annex-fuzztest 1
.SH NAME
git\-annex fuzztest \- generates fuzz test files
.PP
.SH SYNOPSIS
git annex fuzztest
.PP
.SH DESCRIPTION
Generates random changes to files in the current repository,
for use in testing the assistant. This is dangerous, so it will not
do anything unless \-\-forced.
.PP
.SH SEE ALSO
git\-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

