.TH git-annex-rekey 1
.SH NAME
git\-annex rekey \- change keys used for files
.PP
.SH SYNOPSIS
git annex rekey \fB[file key ...]\fP
.PP
.SH DESCRIPTION
This plumbing\-level command is similar to migrate, but you specify
both the file, and the new key to use for it.
.PP
Multiple pairs of file and key can be given in a single command line.
.PP
.SH OPTIONS
.IP "\fB\-\-force\fP"
.IP
Allow rekeying of even files whose content is not currently available.
Use with caution.
.IP
.SH OPTIONS
.SH SEE ALSO
git\-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

