.TH git-annex-indirect 1
.SH NAME
git\-annex indirect \- switch repository to indirect mode
.PP
.SH SYNOPSIS
git annex indirect
.PP
.SH DESCRIPTION
Switches a repository back from direct mode to the default, indirect
mode.
.PP
Some systems cannot support git\-annex in indirect mode, because they
do not support symbolic links. Repositories on such systems instead
default to using direct mode.
.PP
.SH SEE ALSO
git\-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

