.TH git-annex-vpop 1
.SH NAME
git\-annex vpop \- switch back to previous view
.PP
.SH SYNOPSIS
git annex vpop \fB[N]\fP
.PP
.SH DESCRIPTION
Switches from the currently active view back to the previous view.
Or, from the first view back to original branch.
.PP
The optional number tells how many views to pop.
.PP
.SH SEE ALSO
git\-annex(1)
.PP
git\-annex\-view(1)
.PP
git\-annex\-vfilter(1)
.PP
git\-annex\-vadd(1)
.PP
git\-annex\-vcycle(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

