.TH git-annex-proxy 1
.SH NAME
git\-annex proxy \- safely bypass direct mode guard
.PP
.SH SYNOPSIS
git annex proxy \fB\-\- git cmd [options]\fP
.PP
.SH DESCRIPTION
Only useful in a direct mode repository, this runs the specified git
command with a temporary work tree, and updates the working tree to
reflect any changes staged or committed by the git command.
.PP
For example, to revert the most recent change that was committed
to the repository:
.PP
 git annex proxy \-\- git revert HEAD
.PP
To check out a past version of the repository:
.PP
 git annex proxy \-\- git checkout HEAD^^
.PP
To rename a directory:
.PP
 git annex proxy \-\- git mv mydir newname
.PP
.SH SEE ALSO
git\-annex(1)
.PP
git\-annex\-direct(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

