.TH git-annex-describe 1
.SH NAME
git\-annex describe \- change description of a repository
.PP
.SH SYNOPSIS
git annex describe repository description
.PP
.SH DESCRIPTION
Changes the description of a repository.
.PP
The repository to describe can be specified by git remote name or
by uuid. To change the description of the current repository, use
"here".
.PP
Repository descriptions are displayed by git\-annex in various places.
They are most useful when git\-annex knows about a repository, but there is
no git remote corresponding to it.
.PP
.SH SEE ALSO
git\-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

