.TH git-annex-setpresentkey 1
.SH NAME
git\-annex setpresentkey \- change records of where key is present
.PP
.SH SYNOPSIS
git annex setpresentkey \fBkey uuid [1|0]\fP
.PP
.SH DESCRIPTION
This plumbing\-level command changes git\-annex's records about whether
the specified key's content is present in a remote with the specified uuid.
.PP
Use 1 to indicate the key is present, or 0 to indicate the key is
not present.
.PP
.SH SEE ALSO
git\-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

