.TH git-annex-group 1
.SH NAME
git\-annex group \- add a repository to a group
.PP
.SH SYNOPSIS
git annex group \fBrepository groupname\fP
.PP
.SH DESCRIPTION
Adds a repository to a group, such as "archival", "enduser", or "transfer".
The groupname must be a single word.
.PP
Omit the groupname to show the current groups that a repository is in.
.PP
There are some standard groups that have different default preferred content
settings. See <https://git\-annex.branchable.com/preferred_content/standard_groups/>
.PP
A repository can be in multiple groups at the same time.
.PP
.SH SEE ALSO
git\-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

