.TH git-annex-addunused 1
.SH NAME
git\-annex addunused \- add back unused files
.PP
.SH SYNOPSIS
git annex addunused \fB[number|range ...]\fP
.PP
.SH DESCRIPTION
Adds back files for the content corresponding to the numbers or ranges,
as listed by the last \fBgit annex unused\fP. 
.PP
The files will have names starting with "unused."
.PP
.SH SEE ALSO
git\-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

