.TH git-annex-uninit 1
.SH NAME
git\-annex uninit \- de\-initialize git\-annex and clean out repository
.PP
.SH SYNOPSIS
git annex uninit
.PP
.SH DESCRIPTION
Use this to stop using git annex. It will unannex every file in the
repository, and remove all of git\-annex's other data, leaving you with a
git repository plus the previously annexed files.
.PP
.SH SEE ALSO
git\-annex(1)
.PP
git\-annex\-unannex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

