.TH git-annex-lock 1
.SH NAME
git\-annex lock \- unco unlock command
.PP
.SH SYNOPSIS
git annex lock \fB[path ...]\fP
.PP
.SH DESCRIPTION
Use this to undo an unlock command if you don't want to modify
the files, or have made modifications you want to discard.
.PP
.SH OPTIONS
.IP "file matching options"
.IP
The git\-annex\-matching\-options(1)
can be used to specify files to lock.
.IP
.SH SEE ALSO
git\-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

