.TH git-annex-findref 1
.SH NAME
git\-annex findref \- lists files in a git ref
.PP
.SH SYNOPSIS
git annex findref \fB[ref]\fP
.PP
.SH DESCRIPTION
This is very similar to the \fBgit\-annex find\fP command, but instead of
finding files in the current work tree, it finds files in the
specified git ref.
.PP
.SH OPTIONS
Same as git\-annex\-find(1)
.PP
.SH SEE ALSO
git\-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

