#!/usr/bin/perl
use Digest::SHA;
my %m;
while (<>) {
	chomp;
	my ($size, $email) = m/(\d+): (.*)/;
	if (exists $m{$email}) {
		$m{$email}+=$size;
	}
	else {
		$m{$email}=$size;
	}
}

foreach my $email (keys %m) {
	my $sha1;
	if ($email=~/ \(unregistered\)/) {
		$sha1="N/A";
	}
	else {
		$sha1=Digest::SHA::sha1_hex($email);
	}
	my $obscuredemail=$email;
	$obscuredemail=~s/[+@].*//;

	my $size=$m{$email};
	my $tbsize=int($size / 10000000000) / 100;

	print "${tbsize}TB $sha1 $obscuredemail\n";
}
