#!/usr/bin/perl
my $pubkeys_dir=shift;

my %m;
foreach my $f (<$pubkeys_dir/*/pubkeys>) {
	open (IN, "<", $f);
	while (<IN>) {
		chomp;
		my ($sshkeytype, $sshkey, $email, $uuid) = split(' ', $_, 4);
		$m{$uuid} = $email;
	}
	close IN;
}

while (<>) {
	chomp;
	my ($size, $uuid, $desc) = split(' ', $_, 3);
	my $email=$m{$uuid};
	if (! defined $email) {
		$desc=~s/^-- //;
		$desc=~s/@.*//;
		$email="$desc (unregistered)";
	}
	print "$size $email\n" if $size > 0;
}
